Added: Cart and Wishlist functionality
hussiantabha/chai-storer-react pull request #5
Opened 2022-03-31 05:55 UTC by hussiantabha

Now you can add, delete, increase and decrease quantity in cart also you can add and delete items in Wishlist

2022-03-31 06:20 UTC, Manju-sree requested changes
Its good to see you have used authorization and proper folder structure for each component, got to see many useState in code, try to implement useReducer when there are many states. and also try to add more description in review Comment and please provide login credentials. i can see that products are not moving from products page to wishlist and cart page due to auth. and please add favicon and title to your project.

2022-03-31 06:52 UTC, hussiantabha commented
> Its good to see you have used authorization and proper folder structure for each component, got to see many useState in code, try to implement useReducer when there are many states. and also try to add more description in review Comment and please provide login credentials. i can see that products are not moving from products page to wishlist and cart page due to auth. and please add favicon and title to your project.

Here are the login details 
email: sa
password: sa

2022-04-01 06:27 UTC, Bharatrathod-81 approved these changes

2022-04-01 06:27 UTC, Bharatrathod-81 commented on src/Context/Context.js
>      // console.log(sessionStorage.getItem("token"));
comment can be removed

2022-04-07 16:11 UTC, merged